version: "3.7"
services:
  db:
    container_name: local_mysql_db
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=develop
      - MYSQL_TCP_PORT=3306
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
  my_admin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1